---
apiVersion: v1
kind: Secret
metadata:
  name: postgresagent
type: Opaque
stringData:
  host: {{ .Values.postgresql.host }}
  user: {{ .Values.postgresql.user }}
  password: {{ .Values.postgresql.password }}
  database: {{ .Values.postgresql.dbname }}