{
 "title": "Postgres Statistics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Queries",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect application_name,\n       extract(epoch from age(now(), xact_start)) as age,\n       query from pg_stat_activity\n where query not like '%grafana ignore%'\n   and state='active'\norder by query_start desc"
    }
   ]
  },
  {
   "title": "Transactions until wraparound vacuum",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nSELECT\n  relname as table,\n  least((SELECT setting::int FROM pg_settings WHERE name = 'autovacuum_freeze_max_age') - age(relfrozenxid), \n        (SELECT setting::int FROM pg_settings WHERE name = 'autovacuum_multixact_freeze_max_age') - mxid_age(relminmxid))\n        tx_before_wraparound_vacuum,\n  pg_stat_get_last_autovacuum_time(c.oid) AS last_autovacuum,\n  age(relfrozenxid) AS xid_age,\n  mxid_age(relminmxid) AS mxid_age\nFROM\n  pg_class c\nWHERE\n  c.relname in ('ethereum_blocks', 'eth_call_cache','subgraph_deployment')\n  and c.relfrozenxid != 0\n"
    }
   ]
  },
  {
   "title": "Autovacuum pressure",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect count(*) as tables_needing_vacuum,\n       -min(tx_before_wraparound_vacuum) as txns_past,\n       min(last_autovacuum) as last_autovacuum\n  from (\n    select oid::regclass::text AS table,\n       least(\n         (select setting::int\n            from pg_settings\n            where name = 'autovacuum_freeze_max_age') - age(relfrozenxid),\n         (select setting::int\n            from pg_settings\n           where name = 'autovacuum_multixact_freeze_max_age')\n                - mxid_age(relminmxid)) as tx_before_wraparound_vacuum,\n       pg_stat_get_last_autovacuum_time(oid) AS last_autovacuum,\n       age(relfrozenxid) AS xid_age,\n       mxid_age(relminmxid) AS mxid_age\n  from pg_class\n where relfrozenxid != 0\n   and oid > 16384\n   and relkind='r') a where a.tx_before_wraparound_vacuum < 0;\n"
    }
   ]
  },
  {
   "title": "Active locks",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nSELECT  a.application_name,\n        coalesce(extract(epoch from age(now(), a.xact_start)), 0) as age,\n        l.relation::regclass,\n        l.mode,\n        l.GRANTED::varchar,\n        l.locktype \"Target\"\nFROM pg_stat_activity a\nJOIN pg_locks l ON l.pid = a.pid\nwhere pg_backend_pid() != a.pid\norder by granted asc, age desc;"
    }
   ]
  },
  {
   "title": "Idle transactions",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect client_addr,\n       application_name,\n       usename,\n       state,\n       extract(epoch from age(now(), xact_start)) as age\n  from pg_stat_activity\n where query not like '%grafana ignore%'\n   and state like '%idle in transaction%'\norder by query_start desc"
    }
   ]
  }
 ]
}